services:
  mongodb:
    image: "mongo:7-jammy"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - serversites_net

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - files:/data
    restart: unless-stopped
    networks:
      - serversites_net

  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped
    networks:
      - serversites_net

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    links:
      - mongodb
      - minio
    ports:
      - 3002:3000
    environment:
      - SERVER_PORT=3002
      - SERVER_SECRET=${SERVER_SECRET}
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333
      - ENDPOINT_URL=ws://${SERVER_ADDRESS}:3333
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - FRONT_URL=http://front:8080
      - INIT_WORKSPACE=demo-tracker
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://localhost:3002
    restart: unless-stopped
    networks:
      - serversites_net

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    links:
      - mongodb
      - minio
      - elastic
      - collaborator
      - transactor
    hostname: front
    ports:
      - 8087:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${SERVER_SECRET}
      - ACCOUNTS_URL=http://${SERVER_ADDRESS}:3002
      - REKONI_URL=http://${SERVER_ADDRESS}:4004
      - CALENDAR_URL=http://${SERVER_ADDRESS}:8095
      - GMAIL_URL=http://${SERVER_ADDRESS}:8088
      - TELEGRAM_URL=http://${SERVER_ADDRESS}:8086
      - UPLOAD_URL=/files
      - TRANSACTOR_URL=ws://${SERVER_ADDRESS}:3333
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws://${SERVER_ADDRESS}:3078
      - COLLABORATOR_API_URL=http://${SERVER_ADDRESS}:3078
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - TITLE=Forging Social Task Management
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - serversites_net

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    links:
      - mongodb
      - minio
      - transactor
    ports:
      - 3078:3078
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=${COLLABORATOR_SECRET}
      - ACCOUNTS_URL=http://account:3002
      - TRANSACTOR_URL=ws://transactor:3333
      - UPLOAD_URL=/files
      - MONGO_URL=mongodb://mongodb:27017
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    restart: unless-stopped
    networks:
      - serversites_net

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    links:
      - mongodb
      - elastic
      - minio
      - rekoni
      - account
    ports:
      - 3333:3333
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=${SERVER_SECRET}
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:9200
      - MONGO_URL=mongodb://mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - REKONI_URL=http://rekoni:4004
      - FRONT_URL=http://localhost:8087
      - SERVER_PROVIDER=ws
      - ACCOUNTS_URL=http://account:3002
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - serversites_net

  rekoni:
    image: hardcoreeng/rekoni-service:latest
    ports:
      - 4004:4004
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped

  web:
    image: r.forgingsocial.com/nginx:latest
    hostname: web
    restart: always
    ports:
      - "50380:80"
      - "50463:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mongodb
      - minio
      - elastic
      - account
      - collaborator
      - front
      - transactor
      - rekoni
    networks:
      - serversites_net

networks:
  serversites_net:
    # driver: bridge # local testing
    external: true # prod

volumes:
  db:
  files:
  elastic:
  etcd:
